server:
  servlet:
    context-path: /ofm
  port: 81
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sakura.ofm.entity
spring:
  datasource:
    name: pcw_blog
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      clear-filters-enable: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.106.186.144:3306/ofm?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    favicon:
      enabled: false
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true



